name: Windows Server 2019

on: 
  workflow_dispatch:
    inputs:
      chrome_access_code:
        description: x
        required: true
      pin:
        description: x
        required: true
jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Run settting file
        run: |
          ./windows_config/setting.ps1
          ${{ github.event.inputs.chrome_access_code }} -pin=${{ github.event.inputs.pin }}
      - name: Windows Server ready to go 
        run: sleep 86400
