name: Windows Server 2019

on: 
  workflow_dispatch:
    inputs:
      chrome_access_code:
        description: & "${Env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" --code="4/0AdQt8qj6Jjiics6BCLL8YzSYQn9r0HtPYdgJwLui1fYjYdEp_0SiS4ci3UeuqFxu6-dm1Q" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$Env:COMPUTERNAME
        required: true
      pin:
        description: 123456
        required: true
jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Run settting file
        run: |
          ./windows_config/setting.ps1
          ${{ github.event.inputs.chrome_access_code }} -pin=${{ github.event.inputs.pin }}
      - name: Windows Server ready to go 
        run: sleep 86400
